server:
  port: 9010

spring:
  application:
    name: LOGIN-SERVICE
  zipkin:
    base-url: http://localhost:9411/zipkin/
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:h2:file:./DB
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update